import { Router } from "express";
import verifyToken from '../Middlewares/verifytokenmiddleware.js';
import { getAllbrands,addBrand, getOneBrand, updateBrand, deleteBrand } from '../Controllers/brandcontroller.js';
const router = Router();
router.get('/',verifyToken,getAllbrands);
router.post('/addbrand',verifyToken,addBrand);
router.get('/getonebrand/:brandId',verifyToken,getOneBrand);
router.put('/updatebrand/:brandId',verifyToken,updateBrand);
router.delete('/deletebrand/:brandId',verifyToken,deleteBrand);
export default router;